# Generated by Django 5.0.6 on 2024-09-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transId', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50, verbose_name='status')),
                ('medium', models.CharField(max_length=50, verbose_name='Medium')),
                ('serviceName', models.CharField(max_length=50, verbose_name='serviceName')),
                ('transType', models.CharField(max_length=50, verbose_name='Transaction Type')),
                ('amount', models.CharField(max_length=50, verbose_name='Amount')),
                ('payerName', models.CharField(max_length=50, verbose_name='Payer Name')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('financialTransId', models.CharField(max_length=50, verbose_name='financialTransId')),
                ('dateInitiated', models.CharField(max_length=50, verbose_name='dateInitiated')),
                ('dateConfirmed', models.CharField(max_length=50, verbose_name='dateConfirmed')),
            ],
        ),
    ]
