# Generated by Django 5.0.6 on 2024-10-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='financialTransId',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='financialTransId'),
        ),
    ]
