# Generated by Django 5.0.6 on 2024-10-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='medium',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Medium'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payerName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payer Name'),
        ),
    ]
